name: Generate docs on push
on:
  push:
    branches:
      - main
jobs:
  build-and-generate:
    runs-on: ubuntu-latest
    name: Build & Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Authorize
        run: |
          git config user.name DocsGenerator
          git config user.email 62028267+47PADO47@users.noreply.github.com
      - name: Generate
        run: npm run docs:push